### ISSUE TITLE
Get rid of codyco-modules/extern/eigen_unsupported

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#118]
In this repository there is a directory that is hosting the `Eigen` LGSM module. 
Given that the ocra modules are not getting LGSM from here, I guess it is safe to remove it? 
@rlober @serena-ivaldi

**Comment by traversaro** [comment]
Can we also get rid of the `src/python` directory? It's use is not explained anywhere, and they are messing up doxygen documentation.

**Comment by rlober** [comment]
As far as I am concerned **yes** for `eigen_unsupported`. I have created a repo for our old eigen 3.0.5 with lgsm [link to repo](https://github.com/ocra-recipes/eigen_3_0_5). So even if you delete it we have a backup. 

As for `src/python` it doesn't look like it has seen much action recently, but since these are all Serena's I will defer to her. My guess is that she doesn't need them anymore, but it may be good to make a backup.

**Comment by traversaro** [comment]
:+1:

**Comment by traversaro** [comment]
Done in https://github.com/robotology/codyco-modules/pull/185 .
