### ISSUE TITLE
Bad estimation of external wrenches: are the measurements from FT reliable?

### ISSUE THREAD

**Issue by DanielePucci** [robotology/codyco-modules#160]
When performing the yoga demo on the left foot starting from a two-feet standing position, the algorithms in charge of estimating the external wrenches sense external forces even if there is no external perturbation exerted on the robot:

![out2](https://cloud.githubusercontent.com/assets/5045846/11394916/47b9f22e-9368-11e5-9d98-1f0612f06485.gif)

The algorithms estimating the external wrenches basically evaluate the "difference" between the robot's model and the measurements coming from the FT sensors to identify an external wrench (@traversaro can add additional and precise details on this). Now, thanks to the work at the modelling level by @fiorisi and @Mick3Lozzo, the model of iCubV2.5 shall be reliable at both kinematics and dynamics level. This means that the focus is on the measurements coming from the FT sensors. Probably,  we need in-situ calibrations of the FT sensors, which may account for platform dependent effect that miscalibrate the FT sensors during the installation procedure.

@francesco-romano @fiandra @iron76

**Comment by traversaro** [comment]
I think this issue can be closed, not because the issue has been  solved, but because the issue of the reliability of the FT sensors measurements is not related at all to the software for estimating the external forces and torques. However, I think that this issue and all the other issues that refer to this one may be of interest for the team that is currently tackling the issue of reliability of FT sensors measurements, including @marcoaccame @Nicogene @triccyx @salvi-mattia @davidetome @simeonedussoni @maurizbo .

**Comment by traversaro** [comment]
It may be an interesting reference also for all the @robotology/iit-dic .
