### ISSUE TITLE
Proper shared library creation

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-modules#42]
This is just a todo item.
We should mark exported symbols in our libraries.
See [this](https://www.gnu.org/software/gnulib/manual/html_node/Exported-Symbols-of-Shared-Libraries.html).

**Comment by traversaro** [comment]
I think we could try the feature described in this blog post: http://www.kitware.com/blog/home/post/939 for shared library creation on Windows as soon as CMake 3.4 is released. It could also be interesting to test it on `icub-main`. It is suboptimal with respect to actually mark exported symbols, but is similar on how things works on *nix system and I never saw anyone of being particularly concerned of symbol visibility issues.

**Comment by traversaro** [comment]
I tested the new CMake option for `icub-main` libraries in https://github.com/robotology/icub-main/pull/243 . 
It seems to be working fine, so I think we can stick to it instead of manually defining symbol visibility. I will add this option to iDynTree and then we can add it to whatever library we like.
